### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by ellistarn** [containership/cerebral#124]
Looks like there hasn't been a new commit for over a year. Can you provide any context for a kubernetes anthropologist?

**Comment by stritt** [comment]
Hi Ellis,

Sadly Containership shut it's doors a year ago. The technology was acquired, but the core team that maintained this is no longer working together. While I still think this was an exciting approach to autoscaling and purposefully didn't follow the k8s guidelines, there are probably better solutions to investigate these days. (I've heard good things about [keda](https://github.com/kedacore/keda))

Here's a blog post one of the engineers who worked on it wrote: https://blog.containership.io/cerebral-vs-kubernetes-cluster-autoscaler/

Good luck with your research!
