### ISSUE TITLE
Don't hardcode prom-exporter=node label selector for prometheus backend

### ISSUE THREAD

**Issue by mattkelly** [containership/cerebral#15]
#### What is the current behavior?
See these discussions:

- https://github.com/containership/cerebral/pull/13#discussion_r238404175
- https://github.com/containership/cerebral/pull/13#discussion_r238404797

#### What is the expected behavior?

We shouldn't hardcode the label selector as it's specific to our setup. Let's see if we can refactor that block of code to use a dynamic label selector built from the Prometheus `targets` response (can be retrieved using `prometheusclient.Targets()`. Or maybe we can somehow grab the `PodIP`s we need directly from the targets.

#### Additional Context

Pulling this into the release so we can try to get it in, but I don't think it should block the release.

**Comment by mattkelly** [comment]
@noah-vienneau is this being worked on, or should we kick it out of this sprint?

**Comment by noah-vienneau** [comment]
@mattkelly It is being worked on, though I'm not sure it will be done before the end of the sprint.

**Comment by mattkelly** [comment]
No worries at all - we can roll it over into the next one, just wanted to make sure that it was in the right progress column :)

**Comment by noah-vienneau** [comment]
@mattkelly Awesome, I should be making significant progress on it over the next few days. Thanks

**Comment by mattkelly** [comment]
Kicked out of release in favor of higher priority items. Plus this isn't a user-facing change, at least for Containership users, so no need to push it into the release.
