### ISSUE TITLE
Add CI to create and push docker image on tag 

### ISSUE THREAD

**Issue by ashleyschuett** [containership/cerebral#46]
### Description

When a new tag/release is created Travis should create a new docker image and push to docker hub if the build is passing.

**Comment by mattkelly** [comment]
A helpful example for building and pushing `latest` from `master` is here:

https://github.com/containership/cluster-manager/pull/10/files

Except this part of the patch is temporarily missing for testing purposes:

https://github.com/containership/cluster-manager/pull/10/commits/9b5b2e45fbbf80c70fc31d991a17c288d0e7aa82

I think we should also push `latest` from `master` here (and `infrastructure-controller`, etc). Hopefully tags/releases and master are all similar.
