### ISSUE TITLE
Cerebral high level architecture diagram rendering incorrectly

### ISSUE THREAD

**Issue by mvertescher** [containership/cerebral#50]
The Cerebral and Kubernetes logos in the [high level architecture diagram](https://github.com/containership/cerebral/blob/assets/cerebral_high_level_architecture.svg) are not rendering properly (they're missing) in the [readme](https://github.com/containership/cerebral#how-cerebral-works):

![image](https://user-images.githubusercontent.com/1649228/50253295-c0cbf000-03b7-11e9-8a14-b4245dce2516.png)

The SVG should render something like: 

![image](https://user-images.githubusercontent.com/1649228/50253567-97f82a80-03b8-11e9-93d2-96672eff57de.png)

Not sure what's causing this, but looks a little strange right now... :thinking:

**Comment by mattkelly** [comment]
Thank you for taking the time to open an issue and point this out, @mvertescher!

I figured it would be best to just switch to a PNG. The PR is here: https://github.com/containership/cerebral/pull/53

Please let us know if you have any other input on the diagram or overall README. All feedback is much appreciated!
