### ISSUE TITLE
Add DigitalOcean Kubernetes AutoscalingEngine

### ISSUE THREAD

**Issue by normanjoyner** [containership/cerebral#52]
#### Why should this feature be added?
As a user of DIgitalOcean's managed Kubernetes service, I want to be able to autoscale my cluster. Currently, there is not a way to set up autoscaling natively on DigitalOcean, nor does the official cluster-autoscaler project have integration.

#### How would you like the feature to work?
The engine should integrate with the DigitalOcean API and support adding and removing node pool capacity.

#### What alternatives have been considered?
N/A

#### Additional Context
Kubernetes nodes launched through DigitalOcean's managed offering are not currently labeled with metadata such as cluster ID, node pool ID, etc. There may be a limitation to the initial version of this integration that requires users to hardcode the engine configuration to include a single node pool to autoscale.

**Comment by mattkelly** [comment]
Good news regarding the limitations mentioned above! DO node pool label syncing is in-progress and should be available soon. See the following issues:

- https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/135
- https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/136

And the PR that's already up to implement it:

- https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/142

This should unblock us from having fully functional autoscaling through the DO Kubernetes offering. 🚀
