### ISSUE TITLE
Address inflexibility related to AutoscalingGroup nodeSelector

### ISSUE THREAD

**Issue by normanjoyner** [containership/cerebral#71]
#### What is the current behavior?
When a user defines an `AutoscalingGroup`, they do so by specifying a `nodeSelector` to target a subset of cluster nodes to collect metrics against. Since the `nodeSelector` is an arbitrary key/value label pair on a node, a user is able to create `AutoscalingGroup`s that span logical "node pools", as implemented by the engine (e.g. Containership, DigitalOcean, etc).

This is flexible in that it allows users to arbitrarily remap the concept of a "node pool". For example, a user could make a single `AutoscalingGroup` out of an entire Kubernetes cluster, regardless of the number of underlying "node pools". Doing so reinforces Cerebral concepts such as a `scalingStrategy` in that Cerebral's engine implementations could be intelligent enough to make decisions such as:
* scale up the pool with the least expensive nodes
* scale down the pool with the most expensive nodes
* scale up the pool with the "largest" instance type
* ... and so on

However, in the current implementation, we expect the `nodeSelector` as defined by the user, to match that which is defined by the engine implementation, and hold the pool ID. 

The Containership engine is a concrete example of this:
https://github.com/containership/cerebral/blob/3b93cf7ba12040fda0ac7285cb416eba1ec11723/pkg/autoscaling/engines/containership/containership.go#L94

Additionally, the DigitalOcean engine mimics this limitation by assuming if a `nodeSelector` is supplied on the `AutoscalingGroup`, the end user must also specify the same selector on the engine, and it still must point to a label holding the node pool ID:
https://github.com/containership/cerebral/blob/3b93cf7ba12040fda0ac7285cb416eba1ec11723/pkg/autoscaling/engines/digitalocean/digitalocean.go#L247

#### What is the expected behavior?
If an engine must be opinionated about how `AutoscalingGroup`s are defined, it should be explicitly stated that an `AutoscalingGroup` is a one-to-one map to the concept of a "node pool". In this model, it no longer makes sense for the user to define the composition of an `AutoscalingGroup` through a `nodeSelector`, and we should use a concept similar to a `topologyKey`.

However, since the entire `nodeSelector` is passed through to the engine from the scale manager, I would expect we can first reselect the related nodes, and expect a well-defined label to exist on all of those nodes (e.g. `containership.io/node-pool-id` in the case of the Containership engine).
https://github.com/containership/cerebral/blob/cbb40c31a889d5485a7a4a167c5eeb69883652ce/pkg/controller/scale_manager.go#L258

#### Additional Context
N/A

**Comment by mattkelly** [comment]
As discussed in Slack, we'll move forward with this. The user-specified `nodeSelectors` for an ASG will be decoupled from the engine. The engine will hardcode the label key(s) required to get the provider-specific "node pool ID" (for example) from the node chosen via the scaling strategy. If, in the future, it's determined that this key should be able to be overridden for some reason, we can add it as a configuration item for the engine.

To be absolutely clear, the scaling operation should look like this:

1. Select all nodes for the `nodeSelector` (specified by user in ASG)
2. From this list of candidate nodes, choose one according to the scaling strategy (e.g. random, largest instance size, ...)
3. Get the provider-specific "node pool ID" (for example) from the hardcoded key in the engine
4. Make a request to the provider to scale using the metadata acquired in (3) to identify the pool
