### ISSUE TITLE
Downscale only if given test/check passes

### ISSUE THREAD

**Issue by kazilotus** [containership/cerebral#82]
#### Why should this feature be added?
If a worker node is made for long running jobs, such as video processing, exporting large reports, etc, scaling down mid process will leave the job incomplete and/or probably in a broken state without an error log.

#### How would you like the feature to work?
The autoscaler could run some checks, for example probe an http endpoint in the node, or check for a label in a certain pod in the node. And if the check fails, try testing the other nodes for downscaling.

#### What alternatives have been considered?
Right now the only temporary solution I can think of is to 
- set the scale down threshold to 0
- create a bash script to run the required checks suggested above
- create a cron script to check prometheus for downscaling threshold
- then delete the node using the node providers api

**Comment by mattkelly** [comment]
@kazilotus thank you for the feedback. Unfortunately, this is not something we plan to support.

In the case of long-running jobs, we recommend either running them in a separate, non-autoscaling node pool or creating jobs that are capable of being interrupted and rescheduled.

**Comment by normanjoyner** [comment]
@kazilotus I proposed a solution to your issue over in #96. I’d love to hear if this adequately satisfies your use case.
