### ISSUE TITLE
Refactor DigitalOcean Autoscaling Engine to use node pool information 

### ISSUE THREAD

**Issue by ashleyschuett** [containership/cerebral#87]
### Description
During the initial implementation of the DigitalOcean autoscaling engine, DigitalOcean did not automatically label nodes with their node pool information. Because of this, the implementation treats the whole cluster as one node pool no matter how many node pools are being used.

#### How would you like the feature to work?
Once the node pool information is added to each node we should refactor the engine to use the node pool label key to know which node pool should be interacted with during scaling events. 

In the [previous ticket](https://github.com/containership/cerebral/issues/52) to add the engine we were tracking the progress of this issue. We can still use as it lists the current issues and discussion the DigitalOcean is having about adding these labels.

**Comment by normanjoyner** [comment]
DigitalOcean is now automatically labeling nodes with the label `doks.digitalocean.com/node-pool-id`, and the value is the node pool UUID, as expected.
